version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: mijn_postgres
    environment:
      POSTGRES_DB: leetcode_manager
      POSTGRES_USER: me
      POSTGRES_PASSWORD: 114514
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
