spring:
  flyway:
    locations: classpath:db/migration
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/leetcode_manager?currentSchema=the_questions
    username: me
    password: 114514
    driver-class-name: org.postgresql.Driver
